name: Backend CI

on:
  push:
    paths:
      - "server/**"

  pull_request:
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Debug Environment
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        run: |
          echo "JWT_SECRET exists? -> $([ -n "$JWT_SECRET" ] && echo YES || echo NO)"
          echo "JWT_EXPIRES_IN exists? -> $([ -n "$JWT_EXPIRES_IN" ] && echo YES || echo NO)"

      - name: Run Tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        run: npm test